# Generated by Django 3.0.6 on 2020-05-07 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_resume', '0005_auto_20200227_1224'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePage',
            fields=[
                ('baseresumepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtail_resume.BaseResumePage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtail_resume.baseresumepage',),
        ),
    ]
